export const SONG_CHANGED = 'SONG_CHANGED';
export const SONG_PRESSED = 'SONG_PRESSED';
export const NEW_SONG_ADDED_TO_HISTORY = 'NEW_SONG_ADDED_TO_HISTORY';
export const PREV_SONG_PRESSED = 'PREV_SONG_PRESSED';
export const NEXT_SONG_PRESSED = 'NEXT_SONG_PRESSED';
export const SHUFFLE_PRESSED = 'SHUFFLE_PRESSED';